# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Development/VHDL/zynq_main_test/zynq_memory_test/zynqexample.srcs/sources_1/bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xci
# IP: The module: 'System_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Development/VHDL/zynq_main_test/zynq_memory_test/zynqexample.srcs/sources_1/bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/Development/VHDL/zynq_main_test/zynq_memory_test/zynqexample.srcs/sources_1/bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xci
# IP: The module: 'System_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Development/VHDL/zynq_main_test/zynq_memory_test/zynqexample.srcs/sources_1/bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
