# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Development/VHDL/combined_zynq_test/zynq_memory_test/zynqexample.srcs/sources_1/bd/System/ip/System_axi_uartlite_0_0/System_axi_uartlite_0_0.xci
# IP: The module: 'System_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Development/VHDL/combined_zynq_test/zynq_memory_test/zynqexample.srcs/sources_1/bd/System/ip/System_axi_uartlite_0_0/System_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Development/VHDL/combined_zynq_test/zynq_memory_test/zynqexample.srcs/sources_1/bd/System/ip/System_axi_uartlite_0_0/System_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Development/VHDL/combined_zynq_test/zynq_memory_test/zynqexample.srcs/sources_1/bd/System/ip/System_axi_uartlite_0_0/System_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Development/VHDL/combined_zynq_test/zynq_memory_test/zynqexample.srcs/sources_1/bd/System/ip/System_axi_uartlite_0_0/System_axi_uartlite_0_0.xci
# IP: The module: 'System_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Development/VHDL/combined_zynq_test/zynq_memory_test/zynqexample.srcs/sources_1/bd/System/ip/System_axi_uartlite_0_0/System_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Development/VHDL/combined_zynq_test/zynq_memory_test/zynqexample.srcs/sources_1/bd/System/ip/System_axi_uartlite_0_0/System_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Development/VHDL/combined_zynq_test/zynq_memory_test/zynqexample.srcs/sources_1/bd/System/ip/System_axi_uartlite_0_0/System_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
