set_property IOSTANDARD LVCMOS25 [get_ports {gpio_rtl_0_tri_o[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_rtl_0_tri_o[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_rtl_0_tri_o[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_rtl_0_tri_o[0]}]
set_property PACKAGE_PIN A16 [get_ports {gpio_rtl_0_tri_o[3]}]
set_property PACKAGE_PIN A17 [get_ports {gpio_rtl_0_tri_o[2]}]
set_property PACKAGE_PIN A18 [get_ports {gpio_rtl_0_tri_o[1]}]
set_property PACKAGE_PIN A19 [get_ports {gpio_rtl_0_tri_o[0]}]

set_property PACKAGE_PIN H19 [get_ports UART0_TX]

set_property PACKAGE_PIN H19 [get_ports UART_TX]
set_property PACKAGE_PIN H20 [get_ports UART_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TX]
