

set_property PACKAGE_PIN N19 [get_ports {gpio_rtl_0_tri_io[0]}]
set_property PACKAGE_PIN N20 [get_ports {gpio_rtl_0_tri_io[1]}]
set_property PACKAGE_PIN R20 [get_ports {gpio_rtl_0_tri_io[2]}]
set_property PACKAGE_PIN R21 [get_ports {gpio_rtl_0_tri_io[3]}]
set_property PACKAGE_PIN J20 [get_ports {gpio_rtl_0_tri_io[4]}]
set_property PACKAGE_PIN K21 [get_ports {gpio_rtl_0_tri_io[5]}]
set_property PACKAGE_PIN M21 [get_ports {gpio_rtl_0_tri_io[6]}]
set_property PACKAGE_PIN M22 [get_ports {gpio_rtl_0_tri_io[7]}]
set_property PACKAGE_PIN L21 [get_ports {gpio_rtl_0_tri_io[8]}]
set_property PACKAGE_PIN L22 [get_ports {gpio_rtl_0_tri_io[9]}]
set_property PACKAGE_PIN J21 [get_ports {gpio_rtl_0_tri_io[10]}]
set_property PACKAGE_PIN J22 [get_ports {gpio_rtl_0_tri_io[11]}]
set_property PACKAGE_PIN E19 [get_ports {gpio_rtl_0_tri_io[12]}]
set_property PACKAGE_PIN E20 [get_ports {gpio_rtl_0_tri_io[13]}]
set_property PACKAGE_PIN H22 [get_ports {gpio_rtl_0_tri_io[14]}]
set_property PACKAGE_PIN G22 [get_ports {gpio_rtl_0_tri_io[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[0]}]

